layout_spectrum: 0.3051815
typography_spectrum: 0.7264529
color:
  saturation: 0.7401797
  lightness: 0.6328507
  brandStrength: 0.1571663
  rhythmicContrast: 0.1393408
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
name: 'PC MAXXX '
